# Generated by Django 5.1.6 on 2025-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_leadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
