# Generated by Django 5.1.6 on 2025-03-22 13:00

import lead.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, validators=[lead.models.only_int]),
        ),
    ]
